"""Global constants for pith."""

from __future__ import annotations

DEFAULT_MCP_PREFIX = "MCP__"
RESERVED_TOOL_PREFIX = DEFAULT_MCP_PREFIX
SOUL_FILE = "SOUL.md"

DEFAULT_MAX_MESSAGES = 20
DEFAULT_MEMORY_TOP_N = 8
DEFAULT_COMPACT_KEEP = 50
DEFAULT_MAX_TOOL_OUTPUT_CHARS = 8_000

OBS_LOG_FILENAME = "events.jsonl"

DEFAULT_API_PORT = 8420
